name: hs-raft
version: 0.1.0.0
github: "bartfrenk/hs-raft"
license: BSD3
author: "Bart Frenk"
maintainer: "bart.frenk@gmail.com"
copyright: "2018 Bart Frenk"

extra-source-files:
- README.md

# Metadata used when publishing your package
synopsis: Raft implementation
category: Distributed

description: >-
  Please see the README on GitHub at <https://github.com/bartfrenk/hs-raft>

dependencies:
- base >= 4.7 && < 5
- distributed-process
- distributed-process-lifted
- distributed-process-simplelocalnet
- distributed-process-p2p
- binary
- mtl
- stm
- network-transport-tcp
- network-transport
- network
- random
- monad-control
- transformers-base
- lens
- exceptions
- time
- containers
- parsec
- haskeline
- optparse-applicative

default-extensions:
  - DuplicateRecordFields
  - NamedFieldPuns
  - LambdaCase
  - MultiWayIf
  - OverloadedStrings

ghc-options: -Wall -fno-warn-name-shadowing

library:
  source-dirs: src

executables:
  raft:
    main: Main.hs
    source-dirs: app/raft
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hs-raft
  raft-control:
    main: Main.hs
    source-dirs: app/control
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hs-raft




tests:
  hs-raft-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hs-raft
